### ISSUE TITLE
1.5.1 seems to break ServiceControl tests

### ISSUE THREAD

**Issue by mauroservienti** [Particular/run-tests-action#10]
ServiceControl tests use the TestCategory (e.g., `TestCategory=Transports.SqlServer`) to segment test runs in different jobs. The [PR to update the action from 1.5.0 to 1.5.1](https://github.com/Particular/ServiceControl/pull/3471) constantly fail with a strange error:

> No test matches the given testcase filter `TestCategory=Transports.SqlServer` in D:\a\ServiceControl\ServiceControl\src\ServiceControl.Transports.Msmq.Tests\bin\Release\net472\ServiceControl.Transports.Msmq.Tests.dll

Notice that there seems to be a mismatch between the tested assembly and the defined filter.

**Comment by mauroservienti** [comment]
Further looking into the changes here and how ServiceControl behaves, the failing builds are connected to:

- https://github.com/Particular/run-tests-action/pull/9

However, ServiceControl uses the test filter to segment tests by transport, so there will always be assemblies for which no tests are found. Should there be a mechanism to opt-out of the new behavior or shall look into changing the way ServiceControl runs tests?

**Comment by mauroservienti** [comment]
Could be addressed by https://github.com/Particular/ServiceControl/pull/3554

**Comment by DavidBoike** [comment]
"Fixed" by https://github.com/Particular/run-tests-action/pull/13 removing the test filter feature.

The solution for https://github.com/Particular/ServiceControl/pull/3471 (and to upgrade to `v1.6.0` which was just tagged) lies in https://github.com/Particular/ServiceControl/pull/3554.
